# SLiM-CZ-V1 Medium Configuration
# Slavic Linguistic integrated Micro-model for Czechia
# ~56M parameters, ~224 MB

# Model Architecture
model:
  vocab_size: 30000
  d_model: 512
  num_heads: 8
  num_layers: 8
  d_ff: 2048
  max_seq_len: 1024
  dropout: 0.1

# Training Parameters
train:
  batch_size: 16
  learning_rate: 0.00005
  weight_decay: 0.01
  betas: [0.9, 0.98]
  eps: 1.0e-9
  warmup_steps: 2000
  max_steps: 200000
  gradient_clip: 1.0
  epochs: 20
  
  # Scheduler
  scheduler: "cosine"
  min_lr: 1.0e-6
  
  # Logging & Checkpointing
  log_every: 100
  eval_every: 1000
  save_every: 5000
  
  # Early Stopping
  patience: 5
  min_delta: 0.001

# Generation Parameters
generation:
  max_new_tokens: 150
  temperature: 0.8
  top_k: 50
  top_p: 0.95
  repetition_penalty: 1.2
  do_sample: true

# Data Configuration
data:
  train_split: 0.90
  val_split: 0.05
  test_split: 0.05
  seq_len: 1024
  stride: 512
  
  # Text Processing
  lowercase: false
  remove_urls: true
  remove_emails: true
  min_line_length: 10
  min_frequency: 3

# Model Info
info:
  name: "SLiM-CZ-V1-Medium"
  description: "Slavic Linguistic integrated Micro-model for Czechia - Medium variant"
  version: "1.0"
  language: "cs"
  estimated_params: "~56M"
  estimated_size: "~224 MB"
  use_case: "Production deployments"
