# SLiM-CZ-V1 Tiny Configuration
# Slavic Linguistic integrated Micro-model for Czechia
# ~3M parameters, ~12 MB

# Model Architecture
model:
  vocab_size: 10000
  d_model: 128
  num_heads: 4
  num_layers: 4
  d_ff: 512
  max_seq_len: 256
  dropout: 0.1

# Training Parameters
train:
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.98]
  eps: 1.0e-9
  warmup_steps: 500
  max_steps: 50000
  gradient_clip: 1.0
  epochs: 5
  
  # Scheduler
  scheduler: "cosine"
  min_lr: 1.0e-6
  
  # Logging & Checkpointing
  log_every: 50
  eval_every: 500
  save_every: 2000
  
  # Early Stopping
  patience: 5
  min_delta: 0.001

# Generation Parameters
generation:
  max_new_tokens: 50
  temperature: 0.8
  top_k: 50
  top_p: 0.95
  repetition_penalty: 1.2
  do_sample: true

# Data Configuration
data:
  train_split: 0.90
  val_split: 0.05
  test_split: 0.05
  seq_len: 256
  stride: 128
  
  # Text Processing
  lowercase: false
  remove_urls: true
  remove_emails: true
  min_line_length: 10
  min_frequency: 2

# Model Info
info:
  name: "SLiM-CZ-V1-Tiny"
  description: "Slavic Linguistic integrated Micro-model for Czechia - Tiny variant"
  version: "1.0"
  language: "cs"
  estimated_params: "~3M"
  estimated_size: "~12 MB"
  use_case: "Testing and debugging"
